---
- name: Benchmark Setup
  hosts: all
  become: yes
  vars:
    working_directory: /root/streaming-benchmarks
  pre_tasks:
    - name: Pre-task to pull git repository
      ansible.builtin.command: git pull origin master
      args:
        chdir: "{{ working_directory }}"
  tasks:
    - name: Setup Kafka
      ansible.builtin.shell: ./stream-bench.sh SETUP_KAFKA
      no_log: true
      args:
        chdir: "{{ working_directory }}"
    - name: Setup Flink
      ansible.builtin.shell: ./stream-bench.sh SETUP_FLINK
      no_log: true
      args:
        chdir: "{{ working_directory }}"
    - name: Setup Spark
      ansible.builtin.shell: ./stream-bench.sh SETUP_SPARK
      no_log: true
      args:
        chdir: "{{ working_directory }}"