---
- name: Initial server setup
  hosts: all
  become: yes
  vars:
    java_home: "{{ lookup('env','JAVA_HOME') }}"
  tasks:
    - name: Update and install necessary packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - net-tools