---
- name: Stream Engine Setup
  hosts: all
  become: yes
  vars:
    working_directory: /root/streaming-benchmarks
  pre_tasks:
    - name: Pre-task to pull git repository
      ansible.builtin.command: git pull origin master
      args:
        chdir: "{{ working_directory }}"