---
- name: Git reset
  hosts: all
  become: yes
  vars:
    working_directory: /root/streaming-benchmarks
  pre_tasks:
    - name: Pre-task to git reset hard head
      ansible.builtin.command: git reset --hard HEAD
      args:
        chdir: "{{ working_directory }}"