---
- name: Kafka broker setup
  hosts: kafka, zookeeper
  become: yes
  vars:
    working_directory: /root/streaming-benchmarks
  pre_tasks:
    - name: Pre-task to pull git repository
      ansible.builtin.command: git pull origin master
      args:
        chdir: "{{ working_directory }}"
  tasks:
    - name: Setup Kafka broker
      ansible.builtin.shell: ./setup.sh kafka
      no_log: true
      args:
        chdir: "{{ working_directory }}"
    - name: Zookeeper setup
      ansible.builtin.shell: ./setup.sh zookeeper
      args:
        chdir: "{{ working_directory }}"